# Generated by Django 5.1.2 on 2024-10-16 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('bird_id', models.AutoField(primary_key=True, serialize=False)),
                ('speciesCode', models.CharField(max_length=50, unique=True)),
                ('sciName', models.CharField(max_length=255)),
                ('comName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('countryCode', models.CharField(max_length=5, unique=True)),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BirdDetail',
            fields=[
                ('birddetail_id', models.AutoField(primary_key=True, serialize=False)),
                ('recording_url', models.URLField(max_length=500)),
                ('spectrogram', models.URLField(max_length=500)),
                ('bird_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singbirds.bird')),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('hotspot_id', models.AutoField(primary_key=True, serialize=False)),
                ('locId', models.CharField(max_length=20, unique=True)),
                ('locName', models.CharField(max_length=255)),
                ('subnationalCode', models.CharField(max_length=10)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latestObsDate', models.DateField(blank=True, null=True)),
                ('numSpAllTime', models.IntegerField()),
                ('countrycode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singbirds.country')),
            ],
        ),
    ]
