# Generated by Django 5.1.2 on 2024-10-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singbirds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='subnationalCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
