# Generated by Django 5.1.2 on 2024-10-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singbirds', '0002_alter_hotspot_subnationalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='hotspots',
            field=models.ManyToManyField(related_name='birds', to='singbirds.hotspot'),
        ),
    ]
