# Generated by Django 5.1.2 on 2024-10-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singbirds', '0004_alter_birddetail_spectrogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birddetail',
            name='spectrogram',
            field=models.ImageField(blank=True, null=True, upload_to='spectrograms/'),
        ),
    ]
